### ISSUE TITLE
build error due to breaking changes in Esphome

### ISSUE THREAD

**Issue by mibcat** [BMOD89/sml#3]
Hi !

I've tried your package but unfortunately getting build error.

Found some hints in the release notes of [Release 2021.9.3](https://esphome.io/changelog/2021.9.0.html?highlight=reset_type#breaking-changes)
Could you please have a look on this issue - thanks!

Best regards,
Michael.

**Comment by BMOD89** [comment]
Hi do not maintain it anymore. Please use https://github.com/alengwenus/esphome_components instead. It should work for you as well!

**Comment by mibcat** [comment]
Ok - thanks for your answer.
